config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'charts#chart'
  devise_for :users, path_names: { sign_in: :login, sign_out: :logout }

  resources :activities
  resources :missions

  get 'chart', to: 'charts#chart'
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    can :manage, :all, user_id: user.id
  end
end

app/models/activity.rb
class Activity < ApplicationRecord
  belongs_to :user
  belongs_to :mission

  validates :duration, presence: true
  validates :date, presence: true

  after_initialize :init_default_date

  def self.to_chart_data(activities)
    return nil if activities.empty?

    data = activities.group(:mission_id).sum(:duration)
    data.transform_keys { |mission_id| Mission.find(mission_id).name }
  end

  def self.users_last_week(user, date_range)
    user.activities.where(date: date_range)
  end

  private

  def init_default_date
    self.date ||= Date.today if new_record?
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/mission.rb
class Mission < ApplicationRecord
  belongs_to :user
  has_many :activities

  validates :name, :duration, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :activities
  has_many :missions
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :authenticate_user!
  before_action :find_activity, only: [:show, :edit, :update, :destroy]

  load_and_authorize_resource

  def index
    @activities = current_user.activities
  end

  def show
  end

  def new
    @activity = Activity.new
    @activity.user = current_user
  end

  def create

    @activity = Activity.new(activity_params)

    @activity.user = current_user
    if @activity.save
      redirect_to chart_path, notice: 'Successfully created'
    else
      flash.now[:alert] = 'Action failed'
      render :new
    end
  end

  def edit
  end

  def update
    if @activity.update(activity_params)
      redirect_to chart_path, notice: 'Successfully updated'
    else
      flash.now[:alert] = 'Action failed'
      render :edit
    end
  end
  
  def destroy
    @activity.destroy

    redirect_to chart_path, notice: 'Successfully deleted'
  end

  private

  def activity_params
    params.require(:activity).permit(:duration, :mission_id, :date)
  end

  def find_activity
    @activity = Activity.find(params[:id])
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  rescue_from CanCan::AccessDenied do |exception|
    respond_to do |format|
      format.html do
        path = current_user ? root_path : new_user_session_path
        redirect_to path, alert: exception.message
      end
      format.json { render json: { error: exception.message }, status: :forbidden }
      format.js { head :forbidden }
    end
  end


end

app/controllers/charts_controller.rb
class ChartsController < ApplicationController
  before_action :authenticate_user!

  def chart
    @activities = Activity.users_last_week(current_user, week_daterange)
    @chart_data = Activity.to_chart_data(@activities)
  end

  private

  def week_daterange
    return Date.today.at_beginning_of_week..Date.today.end_of_week unless params[:start_date]

    start_date = params.fetch(:start_date, Date.today).to_date
    start_date.beginning_of_week..start_date.end_of_week
  end

end

app/controllers/missions_controller.rb
class MissionsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_mission, only: [:show, :edit, :update, :destroy]

  load_and_authorize_resource

  def index
    @missions = current_user.missions
  end

  def show
  end

  def new
    @mission = Mission.new
  end

  def create

    @mission = Mission.new(mission_params)

    @mission.user = current_user
    if @mission.save
      redirect_to missions_path, notice: 'Successfully created'
    else

      flash.now[:alert] = 'Action failed'
      render :new
    end
  end

  def edit
  end

  def update
    if @mission.update(mission_params)
      redirect_to missions_path, notice: 'Successfully updated'
    else
      flash.now[:alert] = 'Action failed'
      render :edit
    end
  end
  
  def destroy
    @mission.destroy

    redirect_to missions_path, notice: 'Successfully deleted'
  end

  private

  def mission_params
    params.require(:mission).permit(:name, :description, :duration)
  end

  def find_mission
    @mission = Mission.find(params[:id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/activity_helper.rb
module ActivityHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chart_helper.rb
module ChartHelper
end

app/helpers/mission_helper.rb
module MissionHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/activities/_activity.html.slim
div.col-sm-4
  div.card.shadow-sm
    div.card-header
      h5.float-start = "Mission: #{activity.mission.name}"
      =button_to '', activity_path(activity), class: "btn-close float-end", type: 'button', aria: { label: 'Delete' }, method: :delete

    div.card-body
      h6.card-subtitle = "Duration: #{activity.duration.strftime("%H:%M")} hour(s)"
      =link_to '', edit_activity_path(activity), class: "link-warning stretched-link"

app/views/activities/_form.html.slim
div.d-flex.justify-content-center 
  = form_with model: @activity, class: "col-md-5", local: true do |f|
    p = render 'shared/errors', resource: @activity

    div class="form-group"
      p
        = f.label :duration, class: "form-label"
        = f.time_field :duration, class: 'form-control'

    div class="form-group"
      p
        = f.label :mission_id, class: "form-label"
        = f.collection_select :mission_id, @activity.user.missions, :id, :name, { prompt: true }, { class: "form-select" }

    div class="form-group"
      p
        = f.label :date, class: "form-label"
        = f.date_field :date, class: 'form-control'
    
    div class="form-group"
      p= f.submit class: "btn btn-primary"

app/views/activities/chart.html.slim
div.row.g-3
  div.chart.col-md-6.col-sm-6
    = pie_chart @chart, title: "Weekly chart",
                        library: { \
                          chart: { backgroundColor: "#c2c2d6"},
                          plotOptions: {\
                            series: {\
                              states: {\
                                hover: { halo: "null" } \
                              }\
                            }\
                          }\
                        }


  div.col-md-6.col-sm-6
    table.table.table-striped.caption-top
      caption= 'List of activities'
      thead
        tr
          th= 'Name'
          th= 'Duration'
          th= 'Date'

      tbody
        -@activities.each do |activity|
          tr
            td= activity.mission.name
            td= activity.duration.strftime("%H:%M")
            td
              div
                = activity.created_at.strftime("%d-%m-%Y")
                = link_to '', activity_path(activity), class: "btn-close float-end", type: 'button', aria: { label: 'Delete' }, method: :delete
      tfoot
        tr.table-dark
          td="Total"
          td= @total_time_spent.strftime("%H:%M")
          td    
          
    div.btn-group
      = link_to 'New activity', new_activity_path, class: "btn btn-outline-secondary"
      = link_to 'New mission', new_mission_path, class: "btn btn-outline-secondary"

app/views/activities/edit.html.slim
p= link_to 'Back', chart_path, class: "btn btn-secondary"
= render 'form'

app/views/activities/index.html.slim
p= link_to 'New activity', new_activity_path, class: "btn btn-success"

div.text-center
  h1 Your weekly activities

div.row.g-3
  = render @activities

app/views/activities/new.html.slim
p= link_to 'Back', chart_path, class: "btn btn-secondary"
=render 'form'

app/views/activities/show.html.slim
p= link_to 'Back', activities_path, class: "btn btn-secondary"
= render @activity

app/views/charts/chart.html.slim
div.calendar
  = week_calendar(events: @activities, attribute: :date) do |week, activities|
    = week
    table.table
      thead
          tr
            th= 'Name'
            th= 'Duration'
      tbody
      - activities.each do |activity|
        tr
          td= activity.mission.name
          td= activity.duration.strftime("%H:%M")

div.row.g-3
  div.chart.col-md-6.col-sm-6
    = pie_chart @chart_data, title: "Weekly chart",
                        library: { \
                          chart: { backgroundColor: "#c2c2d6"},
                          plotOptions: {\
                            series: {\
                              states: {\
                                hover: { halo: "null" } \
                              }\
                            },\
                            pie: { borderWidth: 0 }\
                          }\
                        }


  div.col-md-6.col-sm-6
    table.table.table-striped.caption-top
      caption= 'List of activities'
      thead
        tr
          th= 'Name'
          th= 'Duration'
          th= 'Date'

      tbody
        -@activities.each do |activity|
          tr
            td= activity.mission.name
            td= activity.duration.strftime("%H:%M")
            td
              div
                = activity.date.strftime("%d-%m-%Y")
              span.text-end
                = link_to 'Edit', edit_activity_path(activity)
                = button_to '', activity_path(activity), class: "btn-close float-end", type: 'button', aria: { label: 'Delete' }, method: :delete
      tfoot
        tr.table-dark
          td="Total"
          - if @activities.empty?
            td= "00:00"
          - else
            td= @activities.sum(:duration).delete_suffix(':00')
          td    
          
    div.btn-group
      = link_to 'New activity', new_activity_path, class: "btn btn-outline-secondary"
      = link_to 'New mission', new_mission_path, class: "btn btn-outline-secondary"

app/views/layouts/application.html.slim
doctype html
html
  head
    meta charset="utf-8"
    
    title=Weekly
    =csrf_meta_tags
    =csp_meta_tag

    =stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    =javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  

  body
    =render 'shared/navbar'

    main
      div.container.px-5
        p.alert-success.rounded= notice
        p.alert-danger.rounded= alert
        =yield
      
    / =render 'shared/footer'
    

  

app/views/missions/_form.html.slim
div.d-flex.justify-content-center 
  = form_with model: @mission, class: "col-md-5", local: true do |f|
    p = render 'shared/errors', resource: @mission

    div class="form-group"
      p
        = f.label :name, class: "form-label"
        = f.text_field :name, class: 'form-control'

    div class="form-group"
      p
        = f.label :description, class: "form-label"
        = f.text_field :description, class: 'form-control'

    div class="form-group"
      p
        = f.label :duration, class: "form-label"
        = f.time_field :duration, class: 'form-control', placeholder: 'hh:mm'
    
    div class="form-group"
      p= f.submit class: "btn btn-primary"

app/views/missions/_mission.html.slim
div.col-sm-4
  div.card.shadow-sm
    div.card-header
      h5.float-start= "Mission name: #{mission.name}"
      =button_to '', mission_path(mission), class: "btn-close float-end", type: 'button', aria: { label: 'Delete' }, method: :delete

    div.card-body
      div.card-text
      
        h5.card-title = "Description: #{mission.description}"
        h6.card-subtitle = "Duration: #{mission.duration.strftime("%H:%M")} hour(s)"

        =link_to '', edit_mission_path(mission), class: "link-warning stretched-link"

app/views/missions/edit.html.slim
p= link_to 'Back', missions_path, class: "btn btn-secondary"
= render 'form'

app/views/missions/index.html.slim
p= link_to 'New mission', new_mission_path, class: "btn btn-success"

div.text-center
  h1 Your weekly missions

div.row.g-3
  = render @missions

app/views/missions/new.html.slim
p= link_to 'Back', missions_path, class: "btn btn-secondary"
=render 'form'

app/views/missions/show.html.slim
p= link_to 'Back', missions_path, class: "btn btn-secondary"
= render @mission

app/views/shared/_errors.html.slim
- if resource&.errors.present?
  b= "#{resource.errors.count} error(s) detected"
  ul
    -resource.errors.full_messages.each do |message|
      li=message

app/views/shared/_footer.html.slim
footer.footer.mt-auto.py-3
  div.container
    ="Hello footer"

app/views/shared/_navbar.html.slim
header.bg-white.border-bottom.shadow-sm
  nav class="navbar navbar-expand-md navbar-dark"
    div.container
      div class="navbar-collapse collapse" id="collapsingNavbar"
        -if user_signed_in?
          ul class="navbar-nav"
            li.nav-item= link_to 'Missions', missions_path, class: "nav-link"
            li.nav-item= link_to 'Chart', chart_path, class: "nav-link"

          ul class="navbar-nav ms-auto"
            li.nav-item= link_to 'Sign out', destroy_user_session_path, method: :delete, class: "nav-link"
        -else
          ul class="navbar-nav ms-auto"
            li.nav-item= link_to 'Login', new_user_session_path, class: "nav-link"
            li.nav-item= link_to 'Signup', new_user_registration_path, class: "nav-link"

app/views/simple_calendar/_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <%= content_tag :tr, class: calendar.tr_classes_for(week) do %>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_month_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_week_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <% if calendar.number_of_weeks == 1 %>
      <span class="calendar-title">Week <%= calendar.week_number %></span>
    <%else%>
        <span class="calendar-title">Week <%= calendar.week_number %> - <%= calendar.end_week %></span>
    <%end%>
        <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>